// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://powwusnypzguwjgwqamw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvd3d1c255cHpndXdqZ3dxYW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTg4NTQsImV4cCI6MjA3Mjk5NDg1NH0.fYLjpvE_9llaK1Hz1P4c1J5id3YLNWe2Jbq2W8M3Ouc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});